---
name: takelage-img-takelpodslim
version: debian-bookworm

local_user: packer_local

images:
  project:
    base_user: debian
    base_tag: bookworm-slim
    target_user: takelwerk
    target_repo: takelpodslim
    packer_template_dir: templates/takelpodslim/docker
    layers:
      - site
